#!/usr/bin/env node
/* Builds the deployable site from samples/record-room.html.
   One script, used by both a local build and the deploy workflow, so the
   page head cannot drift between them. */
const fs=require('fs'), path=require('path'), crypto=require('crypto');
const root=path.resolve(__dirname,'../..');
const src=path.join(root,'samples/record-room.html');
const standalone=path.join(root,'samples/record-room-standalone.html');
const out=path.join(root,'public/index.html');

const body=fs.readFileSync(src,'utf8');
const cut=body.indexOf('</style>');
if(cut<0){console.error('build: no </style> in source');process.exit(1);}
const head=body.slice(0,cut+8), rest=body.slice(cut+8);

const HEAD=`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="color-scheme" content="dark">
<meta name="theme-color" content="#080B0A">
<meta name="description" content="The record book for The 12 Tribes of Gridiron.">
<link rel="manifest" href="/manifest.webmanifest">
<link rel="icon" href="/icon-192.png" sizes="192x192" type="image/png">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="Record Room">
<meta name="mobile-web-app-capable" content="yes">
`;
// GSAP drives the reveals and the count-ups, and has to be in place before
// the page's own script runs. Lenis is a classic script so the page can see
// window.Lenis. The ambient field is a module that imports three only when it
// is going to be used.
// Pinned majors per directive 6.3: gsap@3 (3.15.0), lenis@1, three@0.186.
const VENDOR = `
<script src="/vendor/gsap.min.js"></script>
<script src="/vendor/lenis.min.js" defer></script>
<script src="/vendor/smooth.js" defer></script>
<script type="module" src="/vendor/ambient.js"></script>
`;
const REGISTER=`
<script>
/* Installability, and a shell that still opens with no signal. The service
   worker never touches the Sleeper API: that is a different origin and is
   left to the network every time. */
if('serviceWorker' in navigator){
  addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
}
</script>
`;
const page=HEAD+head+VENDOR+'\n</head>\n<body>\n'+rest+REGISTER+'\n</body>\n</html>\n';
fs.writeFileSync(standalone,page);
fs.mkdirSync(path.join(root,'public'),{recursive:true});
fs.writeFileSync(out,page);

// The cache name carries a hash of the page, so a deploy retires the old one.
const version=crypto.createHash('sha256').update(page).digest('hex').slice(0,12);
const sw=`/* Record Room service worker - generated by samples/tools/build-site.js */
const VERSION='${version}';
const CACHE='record-room-'+VERSION;
const SHELL=['/','/index.html','/manifest.webmanifest',
  '/icon-192.png','/icon-512.png','/apple-touch-icon.png',
  '/vendor/gsap.min.js','/vendor/lenis.min.js','/vendor/smooth.js','/vendor/ambient.js'];
/* three.module.min.js is 670KB and only some visitors ever load it, so it is
   left out of the precache and picked up by the runtime cache on first use. */

self.addEventListener('install',e=>{
  e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting()));
});
self.addEventListener('activate',e=>{
  e.waitUntil(caches.keys()
    .then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k))))
    .then(()=>self.clients.claim()));
});
self.addEventListener('fetch',e=>{
  const req=e.request;
  if(req.method!=='GET')return;
  const url=new URL(req.url);
  if(url.origin!==location.origin)return;        // Sleeper always goes to the network

  if(req.mode==='navigate'){                      // newest page wins, cache is the fallback
    e.respondWith(fetch(req).then(res=>{
      const copy=res.clone();
      caches.open(CACHE).then(c=>c.put('/index.html',copy));
      return res;
    }).catch(()=>caches.match('/index.html').then(r=>r||caches.match('/'))));
    return;
  }
  e.respondWith(caches.match(req).then(hit=>{
    const net=fetch(req).then(res=>{
      if(res&&res.status===200){const copy=res.clone();caches.open(CACHE).then(c=>c.put(req,copy));}
      return res;
    }).catch(()=>hit);
    return hit||net;
  }));
});
`;
fs.writeFileSync(path.join(root,'public/sw.js'),sw);
console.log('built public/index.html ('+page.length+' bytes), sw version '+version);
